// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: true,
  API_URL: '',
  SUPABASE_URL: '',
  SUPABASE_ANON_KEY: '',
  SUPABASE_SERVICE_ROLE_KEY: '',
  RECAPTCHA_V3_STACKBLITZ_KEY: '',
  RECAPTCHA_V2_DUMMY_KEY: '',
};
