// declare var ENV: { 
//   // test: string;
//   apiURL: string;
//   SUPABASE_URL: string;
//   SUPABASE_ANON_KEY: string;
//   SUPABASE_SERVICE_ROLE_KEY: string;
//   RECAPTCHA_V3_STACKBLITZ_KEY: string;
//   RECAPTCHA_V2_DUMMY_KEY: string;
// };

// export const runtimeEnvironment = {
//   // test: ENV.test === '${TEST_ENV}' ? false : ENV.test

//   apiURL: ENV.apiURL === '${apiURL}' ? '' : ENV.apiURL,
//   SUPABASE_URL: ENV.SUPABASE_URL === '${SUPABASE_URL}' ? '' : ENV.SUPABASE_URL,
//   SUPABASE_ANON_KEY: ENV.SUPABASE_ANON_KEY === '${SUPABASE_ANON_KEY}' ? '' : ENV.SUPABASE_ANON_KEY,
//   SUPABASE_SERVICE_ROLE_KEY: ENV.SUPABASE_SERVICE_ROLE_KEY === '${SUPABASE_SERVICE_ROLE_KEY}' ? '' : ENV.SUPABASE_SERVICE_ROLE_KEY,
//   RECAPTCHA_V3_STACKBLITZ_KEY: ENV.RECAPTCHA_V3_STACKBLITZ_KEY === '${RECAPTCHA_V3_STACKBLITZ_KEY}' ? '' : ENV.RECAPTCHA_V3_STACKBLITZ_KEY,
//   RECAPTCHA_V2_DUMMY_KEY: ENV.RECAPTCHA_V2_DUMMY_KEY === '${RECAPTCHA_V2_DUMMY_KEY}' ? '' : ENV.RECAPTCHA_V2_DUMMY_KEY,

// };
